# Unified label catalog (tool-agnostic)
# Sync with .github/workflows/labels-sync.yml via crazy-max/ghaction-github-labeler

# Types
- name: "type:feature"
  color: "0e8a16"
  description: "New functionality"
- name: "type:bug"
  color: "d73a4a"
  description: "Defects & fixes"
- name: "type:docs"
  color: "5319e7"
  description: "Documentation & RFCs"
- name: "type:quality"
  color: "c5def5"
  description: "Refactor, analyzers, test quality"
- name: "type:chore"
  color: "bfdadc"
  description: "Infra/maintenance"

# Size (effort)
- name: "size:XS"
  color: "ededed"
  description: "≤1 hr"
- name: "size:S"
  color: "c2e0c6"
  description: "≈1–3 hrs"
- name: "size:M"
  color: "fbca04"
  description: "≈0.5–1 day"
- name: "size:L"
  color: "f9d0c4"
  description: "≈1–2 days"
- name: "size:XL"
  color: "e99695"
  description: ">2 days"

# Domains
- name: "domain:frontend"
  color: "1d76db"
  description: "UI, UX, rendering, input"
- name: "domain:backend"
  color: "0052cc"
  description: "Services, APIs, frameworks, data"
- name: "domain:infra"
  color: "0e8a16"
  description: "CI/CD, infra-as-code, deployment"
- name: "domain:docs"
  color: "5319e7"
  description: "Documentation & specs"
- name: "domain:test"
  color: "bfe5bf"
  description: "Testing & quality"
- name: "domain:unity"
  color: "ffab70"
  description: "Unity-specific integrations"

# Status
- name: "status:blocked"
  color: "b60205"
  description: "Blocked by another issue/PR"
- name: "status:ready"
  color: "0e8a16"
  description: "All blockers resolved"

# Needs / meta
- name: "needs:tests"
  color: "d4c5f9"
  description: "Add or extend tests"
- name: "needs:design"
  color: "f9d0c4"
  description: "Design/spec work required"
- name: "needs:decision"
  color: "fef2c0"
  description: "Requires product/arch decision"

# Misc
- name: "good first issue"
  color: "7057ff"
  description: "Beginner-friendly entry task"
- name: "integration"
  color: "fb8c00"
  description: "Cross-cutting integration work"
