blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/GiantCroissant-Lunar/winged-bean/tree/main/docs
    about: Browse RFCs, guides, and design docs
  - name: 💬 Discussions
    url: https://github.com/GiantCroissant-Lunar/winged-bean/discussions
    about: Ask questions and discuss ideas
