// <auto-generated />
// Generated by quicktype and modified for System.Text.Json
// To parse this JSON data:
//
//    using ConsoleDungeon.Host.Generated;
//    using System.Text.Json;
//
//    var pluginManifest = JsonSerializer.Deserialize<PluginManifest>(jsonString);

namespace ConsoleDungeon.Host.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Plugin manifest structure (generated from .plugin.json)
    /// </summary>
    public partial class PluginManifest
    {
        [JsonPropertyName("id")]
        public string Id { get; set; } = "";

        [JsonPropertyName("version")]
        public string Version { get; set; } = "";

        [JsonPropertyName("name")]
        public string Name { get; set; } = "";

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("author")]
        public string? Author { get; set; }

        [JsonPropertyName("license")]
        public string? License { get; set; }

        [JsonPropertyName("entryPoint")]
        public EntryPoint EntryPoint { get; set; } = new();

        [JsonPropertyName("dependencies")]
        public Dependencies? Dependencies { get; set; }

        [JsonPropertyName("exports")]
        public Exports? Exports { get; set; }

        [JsonPropertyName("capabilities")]
        public List<string>? Capabilities { get; set; }

        [JsonPropertyName("supportedProfiles")]
        public List<string>? SupportedProfiles { get; set; }

        [JsonPropertyName("loadStrategy")]
        public string? LoadStrategy { get; set; }

        [JsonPropertyName("priority")]
        public int Priority { get; set; }
    }

    public partial class Dependencies
    {
        [JsonPropertyName("plugins")]
        public List<string>? Plugins { get; set; }

        [JsonPropertyName("nuget")]
        public List<NuGetDependency>? Nuget { get; set; }
    }

    public partial class NuGetDependency
    {
        [JsonPropertyName("packageId")]
        public string PackageId { get; set; } = "";

        [JsonPropertyName("version")]
        public string Version { get; set; } = "";

        [JsonPropertyName("optional")]
        public bool Optional { get; set; }

        [JsonPropertyName("reason")]
        public string? Reason { get; set; }
    }

    public partial class EntryPoint
    {
        [JsonPropertyName("dotnet")]
        public string? Dotnet { get; set; }

        [JsonPropertyName("nodejs")]
        public string? Nodejs { get; set; }

        [JsonPropertyName("unity")]
        public string? Unity { get; set; }

        [JsonPropertyName("godot")]
        public string? Godot { get; set; }
    }

    public partial class Exports
    {
        [JsonPropertyName("services")]
        public List<Service>? Services { get; set; }
    }

    public partial class Service
    {
        [JsonPropertyName("interface")]
        public string Interface { get; set; } = "";

        [JsonPropertyName("implementation")]
        public string Implementation { get; set; } = "";

        [JsonPropertyName("lifecycle")]
        public string Lifecycle { get; set; } = "";
    }
}
