---
have_fun: false
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 50
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true
ignore_patterns:
  # Python cache and build artifacts
  - "**/.mypy_cache/**"
  - "**/.ruff_cache/**"
  - "**/.pytest_cache/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/.venv/**"
  - "**/venv/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.egg-info/**"

  # Node.js / JavaScript
  - "**/node_modules/**"
  - "**/bower_components/**"
  - "**/.next/**"
  - "**/.nuxt/**"
  - "**/dist/**"
  - "**/.cache/**"
  - "**/coverage/**"

  # .NET / C#
  - "**/bin/**"
  - "**/obj/**"
  - "**/*.dll"
  - "**/*.exe"
  - "**/*.pdb"
  - "**/packages/**"

  # Unity specific
  - "**/Library/**"
  - "**/Temp/**"
  - "**/Obj/**"
  - "**/Build/**"
  - "**/Builds/**"
  - "**/*.meta"
  - "**/UserSettings/**"
  - "**/Logs/**"

  # Terraform
  - "**/infra/terraform/**/.terraform/**"
  - "**/.terraform.lock.hcl"

  # Lock files and generated files
  - "**/*.lock"
  - "**/package-lock.json"
  - "**/pnpm-lock.yaml"
  - "**/yarn.lock"

  # Binary and media files
  - "**/*.bin"
  - "**/*.so"
  - "**/*.dylib"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.gif"
  - "**/*.ico"
  - "**/*.pdf"

  # Reference projects (external examples)
  - "**/ref-projects/**"

  # IDE and editor files
  - "**/.vs/**"
  - "**/.vscode/**"
  - "**/.idea/**"
  - "**/*.swp"
  - "**/*.swo"
  - "**/*~"

  # Documentation build artifacts
  - "**/docs/_build/**"
  - "**/site/**"

  # Test coverage reports
  - "**/htmlcov/**"
  - "**/.coverage"
  - "**/coverage.xml"
